### ISSUE TITLE
Versioning and Rename

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/GCB-Dockerfiles#21]
We’re cleaning up some of our CWL files in https://github.com/Duke-GCB/bespin-cwl. The CWL tools exclusively use Docker. Part of the cleanup is to specify/document version numbers for the tools. Some of the docker images we’re using are built out of this repo, and while we're specifying versions inside the Dockerfiles, those versions aren't tagged on the Docker images.

I'm proposing a couple changes to improve this:

1. Include version numbers in the automated builds. We can already do this easily and have tested with [fastqc](https://hub.docker.com/r/dukegcb/fastqc/tags/). Right now it just applies tags latest and v0.11.4 to the image built from fastqc/Dockerfile. I propose we rename this Dockerfile to Dockerfile-v0.11.4 and configure the Docker hub automated builds to build v0.11.4 from this file. Then, if we add a new version, that is Dockerfile-v0.11.5, and we configure a build for it. v0.11.4 continues to exist here with the tag v0.11.4. While this sounds relatively labor intensive, we've considered a few other options and still find it to be the most transparent and traceable.

2. Rename this GitHub repo to something like **GCB-Dockerfiles**. The reason is that we’ll be adding Dockerfiles and auto builds for other tools we’re using in exome seq (bwa, GATK), but they may not be relevant to GGR. @alexbarrera, I see that you have a fork of this repo with some recent changes, but otherwise didn’t know how actively the GGR project was using or publicizing this repo.

3. Update the README.md to document the above decisions. The README is displayed on Docker Hub

**Comment by alexbarrera** [comment]
I'm OK with the changes proposed. I'm using the forked repo mostly to keep and up-to-date set of needed scripts to run the GGR workflows, while having them also in Docker images. However, having those images published in DockerHub was not a priority, and I solely relied on you guys doing so (for once, I don't think I can commit to this original repo). 

I think moving forward I can keep using the forked version for the GGR specific additional files, and I could possibly publish the Docker images down the road. Including the version in the Dockerfiles sounds good to me.

**Comment by dleehr** [comment]
Thanks for the quick reply. We'll go ahead with the changes. 

As far as commit access to this repo, holding that back was to encourage review/collaboration through forks/pull requests. We can give write access if you'd like to branch and pull request instead.

**Comment by alexbarrera** [comment]
I don't think I need write access, and I of course love the collaborative PR/merge approach. If I have missed creating a number of PR to merge my changes upstream it has been mostly an oversight for not being a roadblocking factor (as you know, the main usage of the GGR workflows is using HARDAC, a non-Docker environment).

If the plan is to have a more GCB-wide Dockerfile repository, I would definitely like to contribute to it. Beyond the version naming convention, how do you plan to organize the Dockerfiles? I'm trying to visualize where the GGR specific Dockerfiles would go, and more generally the overall structure of the repo.

**Comment by dleehr** [comment]
I'd keep the organization we have now - top-level directories for tools. The only changes would be the aforementioned version naming convention and more tool directories.

Most of what we have now (bedtools, bowtie, fastqc, etc) isn't unique to GGR. We'd just be adding to that with tools we use in other pipelines (gatk, bwa, trim-galore). We could move some of the GGR-specific utilities to a subdirectory, but that's about all I'd suggest.

It wouldn't be for all Dockerfiles (like those we use to run web applications), just genomics/bioinformatics tools we'd use in pipelines.

**Comment by johnbradley** [comment]
@alexbarrera @dleehr Looks like dockerhub will not let you specify custom Dockerfile names for automated builds. I'm going make changes to use subdirectories instead of Dockerfile name suffix.
So for the example earlier in this thread: `fastqc/0.11.4/Dockerfile`.
There is a feature request to add this to dockerhub: https://github.com/docker/hub-feedback/issues/292 but it doesn't look like it is moving. Docker-cloud does support specifying the docker filename, perhaps thats related
