### ISSUE TITLE
Update documentation for CI-built images

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/GCB-Dockerfiles#46]
The README contains some documentation for how to structure the repo, but does not describe the CI build process, the testing scripts, or how a symlink gets translated to tags.

Per #42:

> We need to write up some documentation for practices on how to use this repo. I intended for the CI scripts to cover most of the cases, but expected that for edge cases (seeding these missing images, deleting if necessary) we'd have standards for building/pushing/managing outside of CI, so we didn't have to do things like add blank lines to Dockerfiles.

**Comment by dleehr** [comment]
There is a build-local script that needs to be updated as well. 

The documentation should cover 

1. How to add a new version of an existing image and update latest
2. How to add a new image, including what steps need to be taken on Docker Hub (e.g. do we need to create the repo before pushing to the registry? Can we automate populating the repo info on Docker Hub)
3. How to build locally using the functions in `functions.sh`
4. How to write unittest.yml files

**Comment by dleehr** [comment]
Only members of the Docker Hub **owners** team can create new repos from a `docker push`. So our lower-privileged builder user can only push new versions of existing repos.

There appears to be a mechanism in the Docker Hub API to update the description, but [V1 API is deprecated](https://stackoverflow.com/questions/38070798/where-is-the-new-docker-hub-api-documentation) and they don't seem to be very forthcoming with documentation for V2.

**Comment by johnbradley** [comment]
You also need to give the `cibuild` team `WRITE` access to new repositories or the build will fail.

`https://hub.docker.com/r/dukegcb/<reponame>/~/settings/collaborators/`
